{"name": "test_add[float]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0.3 == 0.30000000000000004\n +  where 0.30000000000000004 = <bound method Calculator.add of <pythoncode.calc.Calculator object at 0x105753eb8>>(0.1, 0.2)\n +    where <bound method Calculator.add of <pythoncode.calc.Calculator object at 0x105753eb8>> = <pythoncode.calc.Calculator object at 0x105753eb8>.add\n +      where <pythoncode.calc.Calculator object at 0x105753eb8> = <testing.test_cal.TestCalc object at 0x105753fd0>.cal", "trace": "self = <testing.test_cal.TestCalc object at 0x105753fd0>, a = 0.1, b = 0.2\nresult = 0.3\n\n    @pytest.mark.parametrize(('a,b,result'),add_datas,ids=adds)\n    def test_add(self, a, b, result ):\n>       assert result == self.cal.add(a, b)\nE       assert 0.3 == 0.30000000000000004\nE        +  where 0.30000000000000004 = <bound method Calculator.add of <pythoncode.calc.Calculator object at 0x105753eb8>>(0.1, 0.2)\nE        +    where <bound method Calculator.add of <pythoncode.calc.Calculator object at 0x105753eb8>> = <pythoncode.calc.Calculator object at 0x105753eb8>.add\nE        +      where <pythoncode.calc.Calculator object at 0x105753eb8> = <testing.test_cal.TestCalc object at 0x105753fd0>.cal\n\ntesting/test_cal.py:41: AssertionError"}, "parameters": [{"name": "a", "value": "0.1"}, {"name": "b", "value": "0.2"}, {"name": "result", "value": "0.3"}], "start": 1595053844139, "stop": 1595053844140, "uuid": "1f737c99-dfd1-4920-916b-f1cdc411c12c", "historyId": "7d9588f950c8cac7c384925a6b88683a", "fullName": "testing.test_cal.TestCalc#test_add[float]", "labels": [{"name": "parentSuite", "value": "testing"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "zhangbijiangdeMacBook-Pro.local"}, {"name": "thread", "value": "23637-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testing.test_cal"}]}